### ISSUE TITLE
Praktikum 9 ül 1 PORT=3001 ei toimi Windowsis

### ISSUE THREAD

**Issue by madiote** [rakenduste-programmeerimine-2019s/rp2019#4]
Praktikum 9 1. ülesandes ei toimi NPM käsus "PORT=3001":

`npm run build && PORT=3001 npm run start`

**Comment by madiote** [comment]
cc @Caupz:
`"start:prelive": "npm run build && set PORT=3001 npm run start"`

**Comment by saarharri** [comment]
https://github.com/facebook/create-react-app/issues/1083

**Comment by madiote** [comment]
Minu testimise kohaselt töötas hoopis `npm run build && set PORT=3001 && npm run start`, vastasel korral ei läinud`npm run start` käima. Võimalik, et on CMD ja PowerShelli erinevus.
