### ISSUE TITLE
Praktikum 10 ül 6 - registreerumise viga ei näidata

### ISSUE THREAD

**Issue by madiote** [rakenduste-programmeerimine-2019s/rp2019#5]
Ülesande 6 raames (videos asukohas `9:08`) loodi teade, mis ütleb, kui registreerumine ebaõnnestus. 
Mingil põhjusel minu koodis seda viga ei kuvata (ka konsooli) ning kasutaja suunatakse sisselogimislehele, kuigi POST-päring saab vastuseks 500 ning veateate `E11000 duplicate key error collection: test.users index: email_1 dup key: { : "email@email.ee" }`.

Minu SignupPage `handleSubmit` funktsioon näeb videoga sarnane välja. Äkki oskate teie öelda, milles võib viga olla? Seotud commit: https://github.com/madiote/rakenduste-programmeerimine/commit/245c5405b8d9da59629b102260ca975d47d3c22c

**Comment by saarharri** [comment]
> index: email_1 dup key: { : "email@email.ee" }.

 Ütleb, et selline email on juba kasutuses. Kontrollige üle kas selline email on juba andmebaasi salvestatud.

**Comment by madiote** [comment]
Jah, peabki tekkima viga, aga toast näitab, et on edukas ja suunab login lehele.

**Comment by saarharri** [comment]
- Kui server tagastab staatuse `200`, siis on Response OK. 
- Kui server tagastab staatuse `500`, `400` jms.., siis on Response NOT OK.
- https://developer.mozilla.org/en-US/docs/Web/API/Response
- Response.ok Read only
Contains a boolean stating whether the response was successful (status in the range 200-299) or not.

Tuleb lisada väike kood, näiteks.
```
    .then(res => {
      if(!res.ok)throw 'signup failed';
      return res.json();
    })
```

**Comment by madiote** [comment]
Viga sai parandatud, tänan!
