### ISSUE TITLE
Praktikum 9 ül 2: Roboto ei tööta prelives/Herokus

### ISSUE THREAD

**Issue by madiote** [rakenduste-programmeerimine-2019s/rp2019#6]
Avastasin, et font Roboto (mis lisati praktikum 9 ül 2 käigus) töötab vaid localhost keskkonnas, s.t. mitte `npm run start:prelive` ning Herokus.

Firefoxi konsool annab 6 viga stiilis 
`downloadable font: rejected by sanitizer (font-family: "Roboto" style:normal weight:300 stretch:100 src index:2) source: http://localhost:3001/ef7c6637c68f269a882e73bcb57a7f6a.woff2` [(SO)](https://stackoverflow.com/questions/37429519/font-awesome-error-downloadable-font-rejected-by-sanitizer)
ning Chromiumi konsool annab 6 viga stiilis 
`Failed to decode downloaded font: http://localhost:3001/2735a3a69b509faf3577afd25bdf552e.woff2` [(SO)](https://stackoverflow.com/questions/30442319/failed-to-decode-downloaded-font)

Kuna font lisati NPM pluginaga, eeldan et CSSi muuta pole vaja vaid viga on milleski muus. Commit: https://github.com/madiote/rakenduste-programmeerimine/commit/0f685d56608709e4715212e3ea1ad23b45f28917

**Comment by saarharri** [comment]
fonts küsitakse valelt URLilt. webpack.config.js faili tuleks lisada

```
      {
        test: /\.(woff|woff2)$/i,
        use: [
          {
            loader: 'file-loader',
            options:{
              outputPath: "static/fonts"
            }
          },
        ],
      },
```
